### ISSUE TITLE
Remove buttons/hide buttons for length/mass changes during swinging

### ISSUE THREAD

**Issue by CyberSickan** [Grupp-25-Mumindalen/Project#56]
Should be able to change weight and length as pendulum moves as this makes things more intuitive. It also makes it easier to see how the pendulum is affected/not affected by changes to it.

Keep in mind that this will affect the success conditions, most notably on the weight challenge.

**Comment by emelieeee** [comment]
Nu toggles dessa knappar av när pendeln svingar så att man inte skall tro att det skall gå att ändra medans den svingar.
